name=uStepper 8b
version=1.0.0
author=uStepper ApS
maintainer=Thomas Olsen (thomas@ustepper.com)
sentence=Library offering support for uStepper 8b
paragraph=uStepper support library
category=Device Control
url=https://github.com/uStepper/uStepper-8b/tree/main
architectures=*
includes=uStepper8b.h,uStepperSLite.h
